targets:
  $default: 
    sources:
    - $package$
    - pubspec.yaml
    - lib/**
    - test/** 
    builders:
      pubspec_generator:
        options:
          output: lib/src/_core/utils/pubspec.yaml.g.dart
      drift_dev:
        generate_for:
          include:
            - lib/src/_core/database/vm/**
        options:
          data_class_to_companions: true
          mutable_classes: false
          # sqlite:
          #  version: "3.35"