targets:
  $default: 
    sources:
    - $package$
    - pubspec.yaml
    - lib/**
    - test/** 
    builders:
      pubspec_generator:
        options:
          output: lib/src/_core/utils/pubspec.yaml.g.dart
