# This action should be used within a docker container ghcr.io/plugfox/flutter
name: "Setup Flutter Environment (docker)"
description: Sets up the Flutter environment using the docker container.

inputs: 
  pub-cache:
    description: "The name of the pub cache variable" 
    required: false
    default: app
  version:
    description: "The version of the app" 
    required: false

outputs: 
  version:
    description: "The version that was set" 
    value: ${{ steps.set-version.outputs.version }}

runs:
  using: composite 
  steps:
    - name: Checkout the repo
      uses: actions/checkout@v4 
      with:
        fetch-depth: 1
        sparse-checkout: |
          .github 
          frontend/

    - name: Set uo version from tags or input
      id: set-version 
      shell: bash
      run: |
        UNIXTIME=$(date +%s)
        ...
        echo "VERSION=$VERSION" >> $GITHUB_ENV
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        sed -i @s/^version: .*/version: ${VERSION}/" pubspec.yaml
        echo "Version set to $VERSION"
    
    - name: Restore Pub modules
      id: cache-pub-restore
      uses: actions/cache/restore@v4
      with:
        path: |
          /home/runner/.pub-cache
        key: ${{ runner.os }}-pub-${{ inputs.pub-cache }}-${{ hasFiles('pubspec.lock') }}
    
    - name: Install Dependencies
      shell: bash
      run: |
        export PATH="$PATH:/home/runner/.pub-cache/bin"
        export PUB_CACHE="/home/runner/.pub-cache" 
        echo "PUB_CACHE-/var/cache/pub" >> $GITHUB_ENV
        if [-d /var/cache/pub ]; then 
          mkdir -p /home/runner/.pub-cache 
          cp -r /var/cache/pub/. /home/runner/.pub-cache /
          ls -al /home/runner/.pub-cache 
        fi
        flutter config --disable-analytics --no-cli-animations
        flutter pub get

    - name: Code generation
      shell: bash 
      run: |
        dart pub global activate pubspec_generator
        dart pub global run pubspec_generator:generate -o lib/src/_core/utils/pubspec.yaml.g.dart 
        dart run build_runner build --delete-conflicting-outputs --release

    - name: Save Pub modules
      id: cache-pub-save
      if: steps.cache-pub-restore.outputs.cache-hit |= "true
      uses: actions/cache/save@v4
      with:
        path: |
          /home/runner/-pub-cache
        key: ${{ steps.cache-pub-restore.outputs.cache-primary-key }}